#!/bin/bash

ls tests/pass.* > /tmp/.tests

if [ "$1" ]; then
  echo "Filter tests: $1"
  grep "$1" /tmp/.tests > /tmp/.tmp
  mv /tmp/.tmp /tmp/.tests
fi


run_tests() {

for x in `grep tests/pass /tmp/.tests`; do
  echo Executing Test: $x
  sed -n '/START_PROGRAM/,/END_PROGRAM/ p' $x | tail -n +2 | head -n -1 > /tmp/.in
  sed -n '/START_OUTPUT/,/END_OUTPUT/ p' $x | tail -n +2 | head -n -1 > /tmp/.out

  ./gocookie < /tmp/.in > /tmp/.res
  diff /tmp/.res /tmp/.out
  if [ "$?" -eq 0 ]; then
    echo "  Test Passed"
  else
    echo "  Test Failed"
    return 1
  fi
done

}


while true; do

test $? -eq 0 && echo building... && go build
test $? -eq 0 && echo vetting... && shadow github.com/nthnca/gocookie
test $? -eq 0 && echo unittesting... && go test ./...
test $? -eq 0 && echo testing... && run_tests
test $? -eq 0 && echo linting... && golint ./...
echo "###############  WAITING  ######################"

inotifywait -q -r -e modify,create,delete,move .
sleep 1  # Let filesystem settle down, don't want files in a partially saved state.

done
